# Generated by Django 4.2.16 on 2024-11-07 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_data", models.CharField(blank=True, default="", max_length=32)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NW", "New"),
                            ("BN", "Banned"),
                            ("SC", "Successful Customer"),
                        ],
                        default="NW",
                        max_length=2,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="CustomerRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_model", models.CharField(blank=True, default="", max_length=32)),
                ("car_vin", models.CharField(blank=True, default="", max_length=32)),
                (
                    "car_tools_name",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "additional_info",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("DF", "Draft"), ("OW", "On work"), ("DN", "Done")],
                        default="DF",
                        max_length=2,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_requests",
                        to="main.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
