# Generated by Django 4.2.16 on 2024-11-07 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customerrequest",
            old_name="car_tools_name",
            new_name="car_part_name",
        ),
    ]
