# Generated by Django 4.2.16 on 2024-11-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_rename_car_tools_name_customerrequest_car_part_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerrequest",
            name="car_city",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="customerrequest",
            name="request_type",
            field=models.CharField(
                choices=[("DY", "Disassembly"), ("BU", "Buy"), ("PT", "Part")],
                default="PT",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="customerrequest",
            name="additional_info",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AlterField(
            model_name="customerrequest",
            name="car_part_name",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
