# Generated by Django 4.2.2 on 2024-11-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_customerrequest_car_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerrequest",
            name="request_type",
            field=models.CharField(
                choices=[("EG", "Engine"), ("BU", "Buy"), ("PT", "Part")],
                default="PT",
                max_length=2,
            ),
        ),
    ]
